Avkdev\ShopListBundle\Entity\Item:
    type: entity
    table: item
    repositoryClass: Avkdev\ShopListBundle\Entity\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        changed_at_idx:
            columns: [ changed_at ]
    fields:
        title:
            type: string
            length: 255
        status:
            type: smallint
            options:
                default: 0
        changedAt:
            type: datetimetz
            column: changed_at
    lifecycleCallbacks:
        prePersist: [ setChangeAtValue, setStatusValue ]
        preUpdate: [ setChangeAtValue ]
